# Generated by Django 5.2.1 on 2025-06-03 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_assignment_name_room_assignment_submissions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='students',
            field=models.ManyToManyField(null=True, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
